name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main", "feature/local-api-server" ]
    paths:
      - 'Android/**'
      - '.github/workflows/build_android.yaml'
  pull_request:
    branches: [ "main", "feature/local-api-server" ]
    paths:
      - 'Android/**'
      - '.github/workflows/build_android.yaml'

jobs:
  build_apk:
    name: Build Android APK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Android/src
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build release APK
        run: ./gradlew :app:assembleRelease

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: google-ai-edge-gallery-local-api-release
          path: Android/src/app/build/outputs/apk/release/app-release.apk
